// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingBusSystem.Infrastructure.Data;

#nullable disable

namespace TrackingBusSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024051717_addDatabase")]
    partial class addDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Name = "Driver",
                            NormalizedName = "DRIVER"
                        },
                        new
                        {
                            Id = "b18be9c0-aa65-4af8-bd17-00bd9344e576",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c18be9c0-aa65-4af8-bd17-00bd9344e577",
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Announce__3214EC07358607F7");

                    b.HasIndex("SenderUserId");

                    b.HasIndex(new[] { "Id" }, "UQ__Announce__3214EC063F58880F")
                        .IsUnique();

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Buses__3214EC0734B94B78");

                    b.HasIndex(new[] { "Id" }, "UQ__Buses__3214EC06E73C215D")
                        .IsUnique();

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.BusLastLocation", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("LastUpdateTimestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("BusId")
                        .HasName("PK__BusLastL__6A0F60B53F6551AF");

                    b.HasIndex(new[] { "BusId" }, "UQ__BusLastL__6A0F60B42694616B")
                        .IsUnique();

                    b.ToTable("BusLastLocations");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idcard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IDCard");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Drivers__3214EC071E7E78E1");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "UQ__Drivers__3214EC06B27217F8")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Routes__3214EC070A209B9A");

                    b.HasIndex(new[] { "Id" }, "UQ__Routes__3214EC067798D6EB")
                        .IsUnique();

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RouteName = "Tuyến Trường Chinh - Âu Cơ"
                        },
                        new
                        {
                            Id = 2,
                            RouteName = "Tuyến Quốc lộ 52"
                        },
                        new
                        {
                            Id = 3,
                            RouteName = "Tuyến Nguyễn Hữu Thọ - Khánh Hội"
                        });
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("DropOffTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("PickupTime")
                        .HasColumnType("time");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Schedule__3214EC07444BB67C");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.StopPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StopPoin__3214EC07447DF06E");

                    b.HasIndex("RouteId");

                    b.HasIndex(new[] { "Id" }, "UQ__StopPoin__3214EC06E20CC330")
                        .IsUnique();

                    b.ToTable("StopPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 10.819554999999999,
                            Longitude = 106.630731,
                            PointName = "Trạm kcn Tân Bình",
                            RouteId = 1,
                            SequenceOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 10.782951000000001,
                            Longitude = 106.642635,
                            PointName = "Trạm bệnh viện Tân Phú",
                            RouteId = 1,
                            SequenceOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 10.759917099999999,
                            Longitude = 106.6796834,
                            PointName = "Đại học sài gòn",
                            RouteId = 1,
                            SequenceOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 10.87335,
                            Longitude = 106.808025,
                            PointName = "Trạm đại học quốc gia",
                            RouteId = 2,
                            SequenceOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 10.849184899999999,
                            Longitude = 106.7543493,
                            PointName = "Trạm ngã tư Thủ Đức",
                            RouteId = 2,
                            SequenceOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 10.759917099999999,
                            Longitude = 106.6796834,
                            PointName = "Đại học sài gòn",
                            RouteId = 2,
                            SequenceOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 10.741214100000001,
                            Longitude = 106.69534280000001,
                            PointName = "Trạm lotte mart q7",
                            RouteId = 3,
                            SequenceOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 10.758583,
                            Longitude = 106.699443,
                            PointName = "Trạm công viên khánh hội",
                            RouteId = 3,
                            SequenceOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 10.759917099999999,
                            Longitude = 106.6796834,
                            PointName = "Đại học sài gòn",
                            RouteId = 3,
                            SequenceOrder = 3
                        });
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Student__3214EC07A694E5CB");

                    b.HasIndex("PointId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "UQ__Student__3214EC06EA2BF211")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.StudentCheckingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckingStatus")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StopPointId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentC__3214EC0723F89E3C");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StopPointId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "Id" }, "UQ__StudentC__3214EC064ECDF52E")
                        .IsUnique();

                    b.ToTable("StudentCheckingHistory", (string)null);
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.UserAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("IsRead")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__UserAnno__3214EC07B0364131");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex(new[] { "Id" }, "UQ__UserAnno__3214EC063CE44EAC")
                        .IsUnique();

                    b.ToTable("UserAnnouncements");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", "SenderUser")
                        .WithMany("SentAnnouncements")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.BusLastLocation", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.Bus", "Bus")
                        .WithOne("BusLastLocation")
                        .HasForeignKey("TrackingBusSystem.Domain.Entities.BusLastLocation", "BusId")
                        .IsRequired()
                        .HasConstraintName("BusLastLocations_fk0");

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Driver", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", "User")
                        .WithOne("Driver")
                        .HasForeignKey("TrackingBusSystem.Domain.Entities.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.Bus", "Bus")
                        .WithMany("Schedules")
                        .HasForeignKey("BusId")
                        .IsRequired()
                        .HasConstraintName("Schedules_fk3");

                    b.HasOne("TrackingBusSystem.Domain.Entities.Driver", "Driver")
                        .WithMany("Schedules")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("Schedules_fk2");

                    b.HasOne("TrackingBusSystem.Domain.Entities.Route", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("Schedules_fk4");

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.StopPoint", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.Route", "Route")
                        .WithMany("StopPoints")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("StopPoints_fk2");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Student", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.StopPoint", "Point")
                        .WithMany("Students")
                        .HasForeignKey("PointId")
                        .IsRequired()
                        .HasConstraintName("Student_fk6");

                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("TrackingBusSystem.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.StudentCheckingHistory", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.Schedule", "Schedule")
                        .WithMany("StudentCheckingHistories")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("StudentCheckingHistory_fk1");

                    b.HasOne("TrackingBusSystem.Domain.Entities.StopPoint", "StopPoint")
                        .WithMany("StudentCheckingHistories")
                        .HasForeignKey("StopPointId")
                        .IsRequired()
                        .HasConstraintName("StudentCheckingHistory_fk5");

                    b.HasOne("TrackingBusSystem.Domain.Entities.Student", "Student")
                        .WithMany("StudentCheckingHistories")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("StudentCheckingHistory_fk2");

                    b.Navigation("Schedule");

                    b.Navigation("StopPoint");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.UserAnnouncement", b =>
                {
                    b.HasOne("TrackingBusSystem.Domain.Entities.Announcement", "Announcement")
                        .WithMany("UserAnnouncements")
                        .HasForeignKey("AnnouncementId")
                        .IsRequired()
                        .HasConstraintName("UserAnnouncements_fk1");

                    b.HasOne("TrackingBusSystem.Domain.Entities.AppUser", "RecipientUser")
                        .WithMany("UserAnnouncements")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Announcement", b =>
                {
                    b.Navigation("UserAnnouncements");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Driver");

                    b.Navigation("SentAnnouncements");

                    b.Navigation("Student");

                    b.Navigation("UserAnnouncements");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Bus", b =>
                {
                    b.Navigation("BusLastLocation");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Route", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("StopPoints");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("StudentCheckingHistories");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.StopPoint", b =>
                {
                    b.Navigation("StudentCheckingHistories");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("TrackingBusSystem.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentCheckingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
